tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
cask_args appdir: "/Applications"

brew "coreutils"
brew "fzf"
brew "gcc"
brew "git"
brew "htop"
brew "jq"
brew "kubernetes-cli"
brew "kubectx"
brew "neovim"
brew "opa"
brew "prettier"
brew "python"
brew "ripgrep"
brew "tmux"
brew "tree"
brew "watch"
brew "wget"
brew "zsh"
cask "alacritty"
cask "docker"
cask "hammerspoon"
cask "visual-studio-code"
