tap "homebrew/bundle"
cask_args appdir: "/Applications"

brew "coreutils"
brew "gcc"
brew "git"
brew "htop"
brew "jq"
brew "kubernetes-cli"
brew "kubie"
brew "neovim"
brew "prettier"
brew "python3"
brew "ripgrep"
brew "tmux"
brew "tree"
brew "watch"
brew "wget"
brew "zsh"
cask "docker"
cask "visual-studio-code"
